package pl.lottoanalyzer.model.lotto;
// Generated 2015-05-25 08:34:08 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * DrawnNumber generated by hbm2java
 */
@Entity
@Table(name="DRAWN_NUMBER"
        ,schema="LOTTO"
        , uniqueConstraints = @UniqueConstraint(columnNames="NUMBER_VAL")
)
public class DrawnNumber  implements java.io.Serializable {


    private Long drawnNumberId;
    private Integer numberVal;
    private Set<Lot> lots = new HashSet<Lot>(0);

    public DrawnNumber() {
    }


    public DrawnNumber(Long drawnNumberId, Integer numberVal) {
        this.drawnNumberId = drawnNumberId;
        this.numberVal = numberVal;
    }
    public DrawnNumber(Long drawnNumberId, Integer numberVal, Set<Lot> lots) {
        this.drawnNumberId = drawnNumberId;
        this.numberVal = numberVal;
        this.lots = lots;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DRAWN_NUMBER_SEQ")
    @SequenceGenerator(name = "DRAWN_NUMBER_SEQ", sequenceName="DRAWN_NUMBER_SEQ")
    @Column(name="DRAWN_NUMBER_ID", unique=true, nullable=false, scale=0)
    public Long getDrawnNumberId() {
        return this.drawnNumberId;
    }

    public void setDrawnNumberId(Long drawnNumberId) {
        this.drawnNumberId = drawnNumberId;
    }


    @Column(name="NUMBER_VAL", unique=true, nullable=false, scale=0)
    public Integer getNumberVal() {
        return this.numberVal;
    }

    public void setNumberVal(Integer numberVal) {
        this.numberVal = numberVal;
    }

    @ManyToMany(fetch=FetchType.LAZY, mappedBy = "drawnNumbers")
    public Set<Lot> getLots() {
        return this.lots;
    }

    public void setLots(Set<Lot> lots) {
        this.lots = lots;
    }




}


