package pl.lottoanalyzer.model.lotto;// default package
// Generated 2015-05-18 09:10:55 by Hibernate Tools 3.6.0


import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * DrawnNumber generated by hbm2java
 */
@Entity
@Table(name="DRAWN_NUMBER"
        ,schema="LOTTO"
        , uniqueConstraints = @UniqueConstraint(columnNames="NUMBER_VAL")
)
public class DrawnNumber  implements java.io.Serializable {

    private Long drawnNumberId;
    private Long numberVal;
    private Set<RelNumberLot> relNumberLots = new HashSet<RelNumberLot>(0);

    public DrawnNumber() {
    }

    public DrawnNumber(Long drawnNumberId, Long numberVal) {
        this.drawnNumberId = drawnNumberId;
        this.numberVal = numberVal;
    }

    public DrawnNumber(Long drawnNumberId, Long numberVal, Set<RelNumberLot> relNumberLots) {
       this.drawnNumberId = drawnNumberId;
       this.numberVal = numberVal;
       this.relNumberLots = relNumberLots;
    }
   
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "DRAWN_NUMBER_SEQ")
    @SequenceGenerator(name = "DRAWN_NUMBER_SEQ", sequenceName="DRAWN_NUMBER_SEQ")
    @Column(name="DRAWN_NUMBER_ID", unique=true, nullable=false, scale=0)
    public Long getDrawnNumberId() {
        return this.drawnNumberId;
    }
    
    public void setDrawnNumberId(Long drawnNumberId) {
        this.drawnNumberId = drawnNumberId;
    }

    
    @Column(name="NUMBER_VAL", unique=true, nullable=false, scale=0)
    public Long getNumberVal() {
        return this.numberVal;
    }
    
    public void setNumberVal(Long numberVal) {
        this.numberVal = numberVal;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="drawnNumber")
    public Set<RelNumberLot> getRelNumberLots() {
        return this.relNumberLots;
    }
    
    public void setRelNumberLots(Set<RelNumberLot> relNumberLots) {
        this.relNumberLots = relNumberLots;
    }




}


