package pl.lottoanalyzer.model.lotto;// default package
// Generated 2015-05-18 09:10:55 by Hibernate Tools 3.6.0


import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Lot generated by hbm2java
 */
@Entity
@Table(name="LOT"
    ,schema="LOTTO"
)
public class Lot  implements java.io.Serializable {

    private Long lotId;
    private Long lotNumber;
    private Date lotDate;
    private Set<RelNumberLot> relNumberLots = new HashSet<RelNumberLot>(0);

    public Lot() {
    }

    public Lot(Long lotId, Long lotNumber, Date lotDate) {
        this.lotId = lotId;
        this.lotNumber = lotNumber;
        this.lotDate = lotDate;
    }

    public Lot(Long lotId, Long lotNumber, Date lotDate, Set<RelNumberLot> relNumberLots) {
       this.lotId = lotId;
       this.lotNumber = lotNumber;
       this.lotDate = lotDate;
       this.relNumberLots = relNumberLots;
    }
   
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "LOT_SEQ")
    @SequenceGenerator(name = "LOT_SEQ", sequenceName="LOT_SEQ")
    @Column(name="LOT_ID", unique=true, nullable=false, scale=0)
    public Long getLotId() {
        return this.lotId;
    }
    
    public void setLotId(Long lotId) {
        this.lotId = lotId;
    }

    
    @Column(name="LOT_NUMBER", nullable=false, scale=0)
    public Long getLotNumber() {
        return this.lotNumber;
    }
    
    public void setLotNumber(Long lotNumber) {
        this.lotNumber = lotNumber;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LOT_DATE",  nullable=false, length=7)
    public Date getLotDate() {
        return this.lotDate;
    }
    
    public void setLotDate(Date lotDate) {
        this.lotDate = lotDate;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="lot")
    public Set<RelNumberLot> getRelNumberLots() {
        return this.relNumberLots;
    }
    
    public void setRelNumberLots(Set<RelNumberLot> relNumberLots) {
        this.relNumberLots = relNumberLots;
    }


    @Override
    public String toString() {
        return ">> "+lotNumber +" > "+lotDate;
    }
}


