package pl.lottoanalyzer.model.lotto;
// Generated 2015-05-25 08:34:08 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * Lot generated by hbm2java
 */
@Entity
@Table(name="LOT"
        ,schema="LOTTO"
)
public class Lot  implements java.io.Serializable {

    private Long lotId;
    private Long lotNumber;
    private Date lotDate;
    private Set<DrawnNumber> drawnNumbers = new HashSet<DrawnNumber>(0);

    public Lot() {
    }


    public Lot(Long lotId, Long lotNumber, Date lotDate) {
        this.lotId = lotId;
        this.lotNumber = lotNumber;
        this.lotDate = lotDate;
    }
    public Lot(Long lotId, Long lotNumber, Date lotDate, Set<DrawnNumber> drawnNumbers) {
        this.lotId = lotId;
        this.lotNumber = lotNumber;
        this.lotDate = lotDate;
        this.drawnNumbers = drawnNumbers;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "LOT_SEQ")
    @SequenceGenerator(name = "LOT_SEQ", sequenceName="LOT_SEQ")
    @Column(name="LOT_ID", unique=true, nullable=false, scale=0)
    public Long getLotId() {
        return this.lotId;
    }

    public void setLotId(Long lotId) {
        this.lotId = lotId;
    }


    @Column(name="LOT_NUMBER", nullable=false, scale=0)
    public Long getLotNumber() {
        return this.lotNumber;
    }

    public void setLotNumber(Long lotNumber) {
        this.lotNumber = lotNumber;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LOT_DATE", nullable=false, length=7)
    public Date getLotDate() {
        return this.lotDate;
    }

    public void setLotDate(Date lotDate) {
        this.lotDate = lotDate;
    }

    @ManyToMany(fetch=FetchType.LAZY )
    @JoinTable(name="REL_NUMBER_LOT", schema="LOTTO", joinColumns = {
            @JoinColumn(name="LOT_ID", nullable=false, updatable=false) }, inverseJoinColumns = {
            @JoinColumn(name="DRAWN_NUMBER_ID", nullable=false, updatable=false) })
    public Set<DrawnNumber> getDrawnNumbers() {
        return this.drawnNumbers;
    }

    public void setDrawnNumbers(Set<DrawnNumber> drawnNumbers) {
        this.drawnNumbers = drawnNumbers;
    }




}


