package pl.lottoanalyzer.model.lotto;// default package
// Generated 2015-05-18 09:10:55 by Hibernate Tools 3.6.0


import javax.persistence.*;

/**
 * RelNumberLot generated by hbm2java
 */
@Entity
@Table(name="REL_NUMBER_LOT"
    ,schema="LOTTO"
)
public class RelNumberLot  implements java.io.Serializable {

    private Long relNumberId;
    private DrawnNumber drawnNumber;
    private Lot lot;

    public RelNumberLot() {
    }

    public RelNumberLot(Long relNumberId, DrawnNumber drawnNumber, Lot lot) {
       this.relNumberId = relNumberId;
       this.drawnNumber = drawnNumber;
       this.lot = lot;
    }
   
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "REL_NUMBER_LOT_SEQ")
    @SequenceGenerator(name = "REL_NUMBER_LOT_SEQ", sequenceName="REL_NUMBER_LOT_SEQ")
    @Column(name="REL_NUMBER_ID", unique=true, nullable=false, scale=0)
    public Long getRelNumberId() {
        return this.relNumberId;
    }
    
    public void setRelNumberId(Long relNumberId) {
        this.relNumberId = relNumberId;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DRAWN_NUMBER_ID", nullable=false)
    public DrawnNumber getDrawnNumber() {
        return this.drawnNumber;
    }
    
    public void setDrawnNumber(DrawnNumber drawnNumber) {
        this.drawnNumber = drawnNumber;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="LOT_ID", nullable=false)
    public Lot getLot() {
        return this.lot;
    }
    
    public void setLot(Lot lot) {
        this.lot = lot;
    }




}


